// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhZxjuw3W5235A7Fb8bNIddumH46JUbA',
    appId: '1:477252807138:web:59bfa4f448e5060e7f71bb',
    messagingSenderId: '477252807138',
    projectId: 'starboy-global-vtu',
    authDomain: 'starboy-global-vtu.firebaseapp.com',
    storageBucket: 'starboy-global-vtu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByd4XuC7y5EP3n1pdplIA_7qxjhlEh8MI',
    appId: '1:477252807138:android:841be66c4941ce407f71bb',
    messagingSenderId: '477252807138',
    projectId: 'starboy-global-vtu',
    storageBucket: 'starboy-global-vtu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDr5aD5OHL47oiwVw3FiKYaNCzvo5kvPU',
    appId: '1:477252807138:ios:ccbe78e5e10cd8137f71bb',
    messagingSenderId: '477252807138',
    projectId: 'starboy-global-vtu',
    storageBucket: 'starboy-global-vtu.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
